apiVersion: v1
kind: Namespace
metadata:
  name: application
  labels:
    benchmark.scenario: simple-01
    pod-security.kubernetes.io/enforce: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: production
  labels:
    benchmark.scenario: simple-01
    pod-security.kubernetes.io/enforce: restricted
