apiVersion: v1
kind: ServiceAccount
metadata:
  name: webapp
  namespace: application
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployer
  namespace: application
automountServiceAccountToken: false
